remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Feitiços Espaciais
description: Uma coleção de performances criadas para refletir conceitos de espaço e se comunicar com os tempo.
show_downloads: "true"
logo: /assets/img/Chaos_Monster_and_Sun_God.png